# See aruw-mcb for Dockerfile associated with the default image

default:
  image: aruw/mcb-2020-gitlab-ci:2020-09-10.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEFAULT_BUILD_ELF_FILE: build/hardware/release/aruw-mcb.elf
  NUM_JOBS: 4

.default_only: &default_only
  - merge_requests
  - master
  - develop

stages:
  - Verification

clang-format:
  stage: Verification
  script:
    - "python3 /run-clang-format.py --clang-format-executable clang-format-10 -r \
       aruw-edu-project/src/ \
       aruw-edu-project/test/ \
       aruw-edu-project/solutions"
  only: *default_only

Soldier Build:
  stage: Verification
  script:
    - cd aruw-edu-project
    - python3 $(which scons) build robot=TARGET_SOLDIER -j${NUM_JOBS}
    - python3 $(which scons) build-tests robot=TARGET_SOLDIER -j${NUM_JOBS}
  only: *default_only

Soldier Solutions Build:
  stage: Verification
  script:
    - cd aruw-edu-project
    - python3 $(which scons) build robot=TARGET_SOLDIER use-solutions=true -j${NUM_JOBS}
    - python3 $(which scons) run-tests robot=TARGET_SOLDIER use-solutions=true -j${NUM_JOBS}
  only: *default_only
